services:
  notification-service:
    image: registry.kifiya.et/qena_baas/multi-tenant-notification-service:development
    container_name: notification-service
    restart: always
    networks:
      - qena-network
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PRODUCTION=False
      - DB=qena_notification_service_db
      - RABBITMQ_URL=amqp://microservices:moMOPx7Rnubed38VfHh8baZ7@machine-two:5672/%2F
      - REDIS_URL=redis://:7c0qpx1d94vdul8y0o1hvp6v@machine-two:6379      
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
  redis-insight:
    image: redis/redisinsight:latest
    container_name: notification-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight-data:/data
    environment:
      - RITRUSTEDORIGINS=http://localhost:8001,http://127.0.0.1:8001
    restart: unless-stopped
    networks:
      - qena-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: notification-redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_URL=redis://:7c0qpx1d94vdul8y0o1hvp6v@machine-two:6379
    restart: unless-stopped
    networks:
      - qena-network

volumes:
  redisinsight-data:

networks:
  qena-network:
    name: qena-network
    external: true