services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT port
      - "8883:8883"    # MQTT/SSL port
      - "15675:15675"  # MQTT over WebSockets
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-network
    restart: unless-stopped
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_mqtt rabbitmq_web_mqtt &&
               rabbitmq-server"

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456@host.docker.internal:5432/qena_notification_service_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://:@redis:6379/0
      - AFROMESSAGE_BASEURL=https://api.afromessage.com/api
      - AFROMESSAGE_APIKEY=eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiYk9uSVBBaVlzcllPVGswRDR1MmlDTktmMUplUHFoZmkiLCJleHAiOjE5MjAwMTg3NzksImlhdCI6MTc2MjI1MjM3OSwianRpIjoiZDY1NGM3MmItZmFjMS00ZjQ5LWE1MmUtMzY4NmZjZjRiZTBkIn0.Gx4_ihJZmGqbYQZyjRZq9e-XoBMgNRkvJr3L388UrBc
      - AFROMESSAGE_SENDER=AfroMessage
      - AFROMESSAGE_FROM=e80ad9d8-adf3-463f-80f4-7c4b39f7f164
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - notification-network
    restart: unless-stopped

networks:
  notification-network:
    driver: bridge
