"""Add unique constraint for message aggregates rollup

Revision ID: 0eb4c093e82a
Revises: 57d8ba0c001f
Create Date: 2026-08-07 19:13:27.156351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb4c093e82a'
down_revision: Union[str, Sequence[str], None] = 'g2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_message_aggregate_rollup', 'message_aggregates_hourly', ['timeBucket', 'tenantId', 'channel', 'provider', 'status'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_aggregate_rollup', 'message_aggregates_hourly', type_='unique')
    # ### end Alembic commands ###
