"""add_tenant_inapp_configurations_table

Revision ID: 4e9ed9d8ab73
Revises: e6fdd993a475
Create Date: 2025-11-14 11:48:23.999925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9ed9d8ab73'
down_revision: Union[str, Sequence[str], None] = 'e6fdd993a475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_inapp_configurations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'provider_name', name='uix_tenant_inapp_provider')
    )
    op.create_index(op.f('ix_tenant_inapp_configurations_id'), 'tenant_inapp_configurations', ['id'], unique=False)
    op.create_table('in_app_outbox',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.String(), nullable=False),
    sa.Column('message_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('provider_attempted', sa.String(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['in_app_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('template_id', 'recipient_user_id', 'idempotency_key', name='uix_in_app_outbox')
    )
    op.create_index(op.f('ix_in_app_outbox_id'), 'in_app_outbox', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_in_app_outbox_id'), table_name='in_app_outbox')
    op.drop_table('in_app_outbox')
    op.drop_index(op.f('ix_tenant_inapp_configurations_id'), table_name='tenant_inapp_configurations')
    op.drop_table('tenant_inapp_configurations')
    # ### end Alembic commands ###
