"""idempotency_key_unique_constraing

Revision ID: 55df0bb094ef
Revises: 302d9f36d9
Create Date: 2025-11-25 12:16:36.974198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55df0bb094ef'
down_revision: Union[str, Sequence[str], None] = '302d9f36d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notifications_id'), table_name='emailNotifications')
    op.create_index(op.f('ix_emailNotifications_id'), 'emailNotifications', ['id'], unique=False)
    op.create_unique_constraint('uix_email_notification', 'emailNotifications', ['templateId', 'recipientEmail', 'idempotencyKey'])
    op.drop_index(op.f('ix_email_outbox_id'), table_name='emailOutbox')
    op.create_index(op.f('ix_emailOutbox_id'), 'emailOutbox', ['id'], unique=False)
    op.create_unique_constraint('uix_email_outbox', 'emailOutbox', ['templateId', 'recipientEmail', 'idempotencyKey'])
    op.drop_index(op.f('ix_email_templates_id'), table_name='emailTemplates')
    op.drop_index(op.f('ix_email_templates_template_name'), table_name='emailTemplates')
    op.create_index(op.f('ix_emailTemplates_id'), 'emailTemplates', ['id'], unique=False)
    op.create_index(op.f('ix_emailTemplates_templateName'), 'emailTemplates', ['templateName'], unique=True)
    op.drop_index(op.f('ix_in_app_notifications_id'), table_name='inAppNotifications')
    op.create_index(op.f('ix_inAppNotifications_id'), 'inAppNotifications', ['id'], unique=False)
    op.create_unique_constraint('uix_in_app_notification', 'inAppNotifications', ['templateId', 'recipientUserId', 'idempotencyKey'])
    op.drop_index(op.f('ix_in_app_outbox_id'), table_name='inAppOutbox')
    op.create_index(op.f('ix_inAppOutbox_id'), 'inAppOutbox', ['id'], unique=False)
    op.drop_index(op.f('ix_in_app_templates_id'), table_name='inAppTemplates')
    op.drop_index(op.f('ix_in_app_templates_template_name'), table_name='inAppTemplates')
    op.create_index(op.f('ix_inAppTemplates_id'), 'inAppTemplates', ['id'], unique=False)
    op.create_index(op.f('ix_inAppTemplates_templateName'), 'inAppTemplates', ['templateName'], unique=True)
    op.drop_index(op.f('ix_providers_provider_name'), table_name='providers')
    op.create_index(op.f('ix_providers_providerName'), 'providers', ['providerName'], unique=True)
    op.drop_index(op.f('ix_sms_notifications_id'), table_name='smsNotifications')
    op.create_index(op.f('ix_smsNotifications_id'), 'smsNotifications', ['id'], unique=False)
    op.create_unique_constraint('uix_sms_notification', 'smsNotifications', ['templateId', 'recipientNumber', 'idempotencyKey'])
    op.drop_index(op.f('ix_sms_outbox_id'), table_name='smsOutbox')
    op.create_index(op.f('ix_smsOutbox_id'), 'smsOutbox', ['id'], unique=False)
    op.create_unique_constraint('uix_sms_outbox', 'smsOutbox', ['templateId', 'recipientNumber', 'idempotencyKey'])
    op.drop_index(op.f('ix_sms_templates_id'), table_name='smsTemplates')
    op.create_index(op.f('ix_smsTemplates_id'), 'smsTemplates', ['id'], unique=False)
    op.drop_index(op.f('ix_tenant_email_configurations_id'), table_name='tenantEmailConfigurations')
    op.create_index(op.f('ix_tenantEmailConfigurations_id'), 'tenantEmailConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenant_inapp_configurations_id'), table_name='tenantInappConfigurations')
    op.create_index(op.f('ix_tenantInappConfigurations_id'), 'tenantInappConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenant_sms_configurations_id'), table_name='tenantSmsConfigurations')
    op.create_index(op.f('ix_tenantSmsConfigurations_id'), 'tenantSmsConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenants_api_keys'), table_name='tenants', postgresql_where='("apiKeys" IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_api_keys'), 'tenants', ['apiKeys'], unique=False, postgresql_where='("apiKeys" IS NOT NULL)')
    op.drop_index(op.f('ix_tenantSmsConfigurations_id'), table_name='tenantSmsConfigurations')
    op.create_index(op.f('ix_tenant_sms_configurations_id'), 'tenantSmsConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenantInappConfigurations_id'), table_name='tenantInappConfigurations')
    op.create_index(op.f('ix_tenant_inapp_configurations_id'), 'tenantInappConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenantEmailConfigurations_id'), table_name='tenantEmailConfigurations')
    op.create_index(op.f('ix_tenant_email_configurations_id'), 'tenantEmailConfigurations', ['id'], unique=False)
    op.drop_index(op.f('ix_smsTemplates_id'), table_name='smsTemplates')
    op.create_index(op.f('ix_sms_templates_id'), 'smsTemplates', ['id'], unique=False)
    op.drop_constraint('uix_sms_outbox', 'smsOutbox', type_='unique')
    op.drop_index(op.f('ix_smsOutbox_id'), table_name='smsOutbox')
    op.create_index(op.f('ix_sms_outbox_id'), 'smsOutbox', ['id'], unique=False)
    op.drop_constraint('uix_sms_notification', 'smsNotifications', type_='unique')
    op.drop_index(op.f('ix_smsNotifications_id'), table_name='smsNotifications')
    op.create_index(op.f('ix_sms_notifications_id'), 'smsNotifications', ['id'], unique=False)
    op.drop_index(op.f('ix_providers_providerName'), table_name='providers')
    op.create_index(op.f('ix_providers_provider_name'), 'providers', ['providerName'], unique=True)
    op.drop_index(op.f('ix_inAppTemplates_templateName'), table_name='inAppTemplates')
    op.drop_index(op.f('ix_inAppTemplates_id'), table_name='inAppTemplates')
    op.create_index(op.f('ix_in_app_templates_template_name'), 'inAppTemplates', ['templateName'], unique=True)
    op.create_index(op.f('ix_in_app_templates_id'), 'inAppTemplates', ['id'], unique=False)
    op.drop_index(op.f('ix_inAppOutbox_id'), table_name='inAppOutbox')
    op.create_index(op.f('ix_in_app_outbox_id'), 'inAppOutbox', ['id'], unique=False)
    op.drop_constraint('uix_in_app_notification', 'inAppNotifications', type_='unique')
    op.drop_index(op.f('ix_inAppNotifications_id'), table_name='inAppNotifications')
    op.create_index(op.f('ix_in_app_notifications_id'), 'inAppNotifications', ['id'], unique=False)
    op.drop_index(op.f('ix_emailTemplates_templateName'), table_name='emailTemplates')
    op.drop_index(op.f('ix_emailTemplates_id'), table_name='emailTemplates')
    op.create_index(op.f('ix_email_templates_template_name'), 'emailTemplates', ['templateName'], unique=True)
    op.create_index(op.f('ix_email_templates_id'), 'emailTemplates', ['id'], unique=False)
    op.drop_constraint('uix_email_outbox', 'emailOutbox', type_='unique')
    op.drop_index(op.f('ix_emailOutbox_id'), table_name='emailOutbox')
    op.create_index(op.f('ix_email_outbox_id'), 'emailOutbox', ['id'], unique=False)
    op.drop_constraint('uix_email_notification', 'emailNotifications', type_='unique')
    op.drop_index(op.f('ix_emailNotifications_id'), table_name='emailNotifications')
    op.create_index(op.f('ix_email_notifications_id'), 'emailNotifications', ['id'], unique=False)
    # ### end Alembic commands ###
