"""sync UserModel

Revision ID: 57d8ba0c001f
Revises: 386ed2a03304
Create Date: 2026-08-05 14:52:35.291039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57d8ba0c001f'
down_revision: Union[str, Sequence[str], None] = '386ed2a03304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emailNotifications_externalId'), 'emailNotifications', ['externalId'], unique=False)
    op.drop_index(op.f('ix_emailOutbox_createdAt_status'), table_name='emailOutbox')
    op.create_index(op.f('ix_inAppNotifications_externalId'), 'inAppNotifications', ['externalId'], unique=False)
    op.drop_index(op.f('ix_inAppOutbox_createdAt_status'), table_name='inAppOutbox')
    op.alter_column('message_aggregates_hourly', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('message_aggregates_hourly', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_msg_agg_unique_bucket'), table_name='message_aggregates_hourly')
    op.create_index(op.f('ix_smsNotifications_externalId'), 'smsNotifications', ['externalId'], unique=False)
    op.drop_index(op.f('ix_smsOutbox_createdAt_status'), table_name='smsOutbox')
    # op.drop_constraint(op.f('uix_tenant_whatsapp_provider'), 'tenantWhatsAppConfigurations', type_='unique')
    # op.create_unique_constraint('uix_tenant_provider', 'tenantWhatsAppConfigurations', ['tenantId', 'providerName'])
    op.alter_column('tenants', 'callbackUrl',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Webhook URL for notification status callbacks (fire-and-forget mode)',
               existing_nullable=True)
    op.alter_column('tenants', 'callbackHeaders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Optional HTTP headers for callback authentication',
               existing_nullable=True)
    op.add_column('user_tenants', sa.Column('role', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_user_tenants_role'), 'user_tenants', ['role'], unique=False)
    op.add_column('users', sa.Column('fullName', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.create_index(op.f('ix_whatsAppNotifications_externalId'), 'whatsAppNotifications', ['externalId'], unique=False)
    op.drop_index(op.f('ix_whatsAppOutbox_createdAt_status'), table_name='whatsAppOutbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_whatsAppOutbox_createdAt_status'), 'whatsAppOutbox', ['createdAt', 'status'], unique=False)
    op.drop_index(op.f('ix_whatsAppNotifications_externalId'), table_name='whatsAppNotifications')
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'fullName')
    op.drop_index(op.f('ix_user_tenants_role'), table_name='user_tenants')
    op.drop_column('user_tenants', 'role')
    op.alter_column('tenants', 'callbackHeaders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Optional HTTP headers for callback authentication',
               existing_nullable=True)
    op.alter_column('tenants', 'callbackUrl',
               existing_type=sa.VARCHAR(),
               comment='Webhook URL for notification status callbacks (fire-and-forget mode)',
               existing_nullable=True)
    op.drop_constraint('uix_tenant_provider', 'tenantWhatsAppConfigurations', type_='unique')
    op.create_unique_constraint(op.f('uix_tenant_whatsapp_provider'), 'tenantWhatsAppConfigurations', ['tenantId', 'providerName'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_smsOutbox_createdAt_status'), 'smsOutbox', ['createdAt', 'status'], unique=False)
    op.drop_index(op.f('ix_smsNotifications_externalId'), table_name='smsNotifications')
    op.create_index(op.f('ix_msg_agg_unique_bucket'), 'message_aggregates_hourly', ['timeBucket', 'tenantId', 'channel', 'provider', 'status'], unique=True)
    op.alter_column('message_aggregates_hourly', 'updatedAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('message_aggregates_hourly', 'createdAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_inAppOutbox_createdAt_status'), 'inAppOutbox', ['createdAt', 'status'], unique=False)
    op.drop_index(op.f('ix_inAppNotifications_externalId'), table_name='inAppNotifications')
    op.create_index(op.f('ix_emailOutbox_createdAt_status'), 'emailOutbox', ['createdAt', 'status'], unique=False)
    op.drop_index(op.f('ix_emailNotifications_externalId'), table_name='emailNotifications')
    # ### end Alembic commands ###
