"""api_key_and_supported_channels_added

Revision ID: 647c9ebb6423
Revises: ff4db9a60419
Create Date: 2025-11-05 11:07:38.077301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '647c9ebb6423'
down_revision: Union[str, Sequence[str], None] = 'ff4db9a60419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_keys', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('supported_channels', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'supported_channels')
    op.drop_column('tenants', 'api_keys')
    # ### end Alembic commands ###
