"""communication_method_added

Revision ID: 6ed3933b70a8
Revises: fcfbd3f6d7bb
Create Date: 2025-11-06 13:18:18.744759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed3933b70a8'
down_revision: Union[str, Sequence[str], None] = 'fcfbd3f6d7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants',
        sa.Column(
            'prefered_communication_method',
            sa.String(),
            nullable=False,
            server_default='rest'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'prefered_communication_method')
    # ### end Alembic commands ###
