"""update_user_model_to_use_fullname

Revision ID: 93cd74a22120
Revises: 16616eadeded
Create Date: 2026-08-07 10:41:47.462512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cd74a22120'
down_revision: Union[str, Sequence[str], None] = '16616eadeded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tenants', sa.Column('role', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_user_tenants_role'), 'user_tenants', ['role'], unique=False)
    op.add_column('users', sa.Column('fullName', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'fullName')
    op.drop_index(op.f('ix_user_tenants_role'), table_name='user_tenants')
    op.drop_column('user_tenants', 'role')
    # ### end Alembic commands ###
