"""add_tenant_inapp_configurations_table

Revision ID: e6fdd993a475
Revises: 6ed3933b70a8
Create Date: 2025-11-14 11:42:46.778356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fdd993a475'
down_revision: Union[str, Sequence[str], None] = '6ed3933b70a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
