"""api_key_and_supported_channel

Revision ID: fcfbd3f6d7bb
Revises: 256769979807
Create Date: 2025-11-05 17:51:21.056219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfbd3f6d7bb'
down_revision: Union[str, Sequence[str], None] = '256769979807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('docs_url', sa.String(), nullable=True),
    sa.Column('test_endpoint', sa.String(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=False),
    sa.Column('ui_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_channel'), 'providers', ['channel'], unique=False)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_provider_name'), 'providers', ['provider_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_provider_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_channel'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
