"""initial_migration_api_key_removed

Revision ID: ff4db9a60419
Revises: 5d786bc50646
Create Date: 2025-11-03 17:49:47.696756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4db9a60419'
down_revision: Union[str, Sequence[str], None] = '5d786bc50646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_sms_configurations', 'api_key')
    op.drop_column('tenant_sms_configurations', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_sms_configurations', sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tenant_sms_configurations', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
